# Generated by Django 4.2.4 on 2023-09-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='emailadress',
            new_name='emailaddress',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='address',
            field=models.TextField(default='Hi'),
            preserve_default=False,
        ),
    ]
